services:
  - type: web
    name: 3DFolio
    env: node
    plan: free
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm run preview
    build:
      artifacts:
        - dist